### PR TITLE
#157803727 Built landing page for users

### PR DESCRIPTION
**Pull request by munyuas**
**What does this PR do?**
It's a landing page for the maintenance app

**Description of task completed?**
Provide links to the signup and sign in pages
Provide some information about the app

**How should this be manually tested?**
$ git clone https://github.com/munyuas/Maintenance-Tracker
On the home direction click index.html  file to view the webpage on a browser

**Any background context you want to provide**
It's the first iteration I'm yet to add responsiveness to it

**What is the relevant pivotal tracker stories?**
 #157803727

**Screenshot**
review

### CODE REVIEW

**Comment by johnmusiu** [comment]
Change base branch to **develop** from master 
Here is a link to help you https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request/

**Comment by munyuas** [comment]
I do that I get the error, "There are no new commits between base branch 'develop' and head branch 'ft-landing-page-157803727"

**Comment by johnmusiu** [comment]
Seems like you might need to rebase. Let me get some links and I'll get back to you

**Comment by munyuas** [comment]
Any links @johnmusiu ?

**Comment by johnmusiu** [comment]
most were not getting me much info on that. I see you closed it. did you
get a solution?

**Comment by munyuas** [comment]
Not really, I created a new branch and moved the content to that temp branch and deleted this one, created another branch with the same name as the one I deleted and moved contents back to it and deleted the temp one.

**Pull request merged**
