### PR TITLE
#157804154 Built signin page for Admins

### PR DESCRIPTION
**Pull request by munyuas**
#**What does this PR do?**
A sign in form to allow a user sign up in the app access services offered by the app.

**Description of task completed?**
Main navigation if a user opts to go the main menu or another section of the page.
Sign in form for a user to sign in to the app.
A sign up detour if the user doesn't have an account.
Simple password hiding and email checking.

**How should this be manually tested?**
$ git clone https://github.com/munyuas/Maintenance-Tracker.git
Clone it and open signin.html to view in browser.

**Any background context you want to provide**
The page will be optimized in a later iteration

**What is the relevant pivotal tracker stories?**
#157804154

**Screenshots**
review

### CODE REVIEW

**Comment by dessHub** [comment]
UI design is fine. However you need to check github best practice [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices)

**Comment by johnmusiu** [comment]
- UI design good, consistent use of colors.
- PR needs some touches for example the git clone command should be like
``` $ git clone .... ```
surround the section with 3 `
- PR descriptions okay

**Comment by alovega** [comment]
To me sign in page  looks great I think its okay 
I don't know about the PR descriptions let me check it out then get back to you

**Comment by munyuas** [comment]
I appreciate your reviews @alovega @johnmusiu

**Pull request merged**
